### PR TITLE
Update documentation and release version

### PR DESCRIPTION
**Pull request by stuwilkins**
Currently work in progress....

### CODE REVIEW

**Comment by stuwilkins** [comment]
@MarkRivers I have updated the docs, and added a FastCCDDoc.html file with the table, could you please have a look and comment?

Thanks!

**Comment by MarkRivers** [comment]
It looks good.  I found a couple of typos:
- In RELEASE.md the phrase "obtained from at" should be "obtained from"
- In the Doc file Berkeley is spelled wrong
- In the Doc.html file the $(P)$(R) is displaying without the dollar signs and the P is in italic font.

**Comment by stuwilkins** [comment]
Fixed the above issues and the doc now has the dollar signs showing for $(P)$(R)

**Comment by MarkRivers** [comment]
Now the dollar signs are correct in the HTML but the \ characters are displayed when the .md file is rendered.  I don't know if it's possible to get it right for both?

**Comment by stuwilkins** [comment]
I think this is because the $ is rendering as maths in the `pandoc` processing.... Investigating

**Comment by stuwilkins** [comment]
Fixed it, FYI the convert is done by 

`pandoc -f markdown-tex_math_dollars -t html --template template.html < FastCCDDoc.md > FastCCDDoc.html` 

This doesn't treat the `$` signs as latex math mode.

**Pull request merged**
