### PR TITLE
Update libcin and sync with new firmware and bring in line with ADCore

### PR DESCRIPTION
**Pull request by stuwilkins**
Do not merge yet ... opening

### CODE REVIEW

**Review by MarkRivers — COMMENTED** [review]
I'm curious why you removed ADBase_settings.req from FastCCD_setting.req and moved it into auto_settings.req?  I think it's a good idea to hide the base class hierarchy from the end-user file (auto_settings.req).

**Comment by stuwilkins** [comment]
Hi @MarkRivers!

For some reason, if ADBase_settings.req on my test system is placed in FastCCD_setting.req then it is not found (I get an error on the iocshell and S&R does not work). Placing it in this place it works? 

I am going through a bit of a refactor at the moment and was going to get back to this later... Any ideas? I agree with your note on where it should be.

S

**Comment by MarkRivers** [comment]
I see that the previous version of FastCCD_settings.req had an error:
```
file "ADBase_settings.req, P=$(P), R=(R)
```
It should be R=$(R) not R=(R).  But it looks like you fixed it before you commented it out?

**Comment by stuwilkins** [comment]
Yes @MarkRivers, I noticed that and fixed it but it still caused problems. I am going to deploy a test to CSX tomorrow, I will let you know if I get an error there too...

**Comment by stuwilkins** [comment]
@MarkRivers I realise that this has lingered for too long and now is a long PR. This is now the production version at NSLS-II, and I have confirmed that it works with the latest master of ADCore. I wonder if we can merge this into master and then future PRs can be much smaller.

@ronpandolfi this is now the version I have tested at CSX. There are a few minor changes to deal with bias files.

**Comment by MarkRivers** [comment]
Both pull requests are merged.  I had to manually edit RELEASE.md to resolve conflicts.

**Pull request merged**
