### PR TITLE
Add documentation to FastCCD driver

### PR DESCRIPTION
**Pull request by stuwilkins**
WIP for the moment. 

@MarkRivers how is the releases tagged or numbered for drivers? Should they follow ADCore or do they number independently?

This PR covers issue #4

### CODE REVIEW

**Comment by MarkRivers** [comment]
> @MarkRivers how is the releases tagged or numbered for drivers? Should they follow ADCore or do they number independently?

They are numbered independently.  If there is a dependency on a particular version of ADCore you should note that in the RELEASE.md file.

**Comment by stuwilkins** [comment]
Thanks @MarkRivers once this is merged and I confirm the version works with our test stand then I will tag as R1.0 then. I will update the RELEASE.md file accordingly. Thanks.

**Comment by MarkRivers** [comment]
Are you ready for me to merge?

**Comment by stuwilkins** [comment]
Yes, thanks. I think any changes would now be minor. I have confirmed that this version is working.

**Comment by stuwilkins** [comment]
Sorry not to merge this branch .... I meant PR #3

**Pull request merged**
